//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKolpakov.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_KolpakovEntities : DbContext
    {
        public static Bd_KolpakovEntities _context;
        public Bd_KolpakovEntities()
            : base("name=Bd_KolpakovEntities")
        {
        }
        public static Bd_KolpakovEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Bd_KolpakovEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Tovary> Tovary { get; set; }
    }
}
