//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKolpakov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        public int Kod { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
    
        public virtual Roli Roli { get; set; }
    }
}
