//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKolpakov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roli
    {
        public int Kod { get; set; }
        public string Role { get; set; }
    
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
