//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKolpakov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovary
    {
        public int Kod { get; set; }
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public string Edenitsa_Izmerenia { get; set; }
        public int Stoimost { get; set; }
        public int Razmer_Maksimalnoy_Skidki { get; set; }
        public string Proizvoditel { get; set; }
        public string Postavshic { get; set; }
        public string Kategorii_Tovara { get; set; }
        public int Deystv_Skidka { get; set; }
        public int Kol_vo_Na_Sklade { get; set; }
        public string Opisanie { get; set; }
        public string Isobragenie { get; set; }
    }
}
